// Mocks generated by Mockito 5.0.14 from annotations
// in restologue/test/features/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restologue/core/data/datasources/home_remote_data_source.dart'
    as _i2;
import 'package:restologue/core/data/models/resto_model.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RestoModel>> getRestos(
          {String? apiUrl, String? endPoint}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getRestos, [], {#apiUrl: apiUrl, #endPoint: endPoint}),
              returnValue:
                  Future<List<_i4.RestoModel>>.value(<_i4.RestoModel>[]))
          as _i3.Future<List<_i4.RestoModel>>);
  @override
  String toString() => super.toString();
}
